function rolesPage(){
 const r=role(),list=matchingRoles(),categories=count(rows('T'),'major_category'),skills=r?skillsFor(r.job_id):[];
 const nearby=r?rows('T').filter(x=>x.job_id!==r.job_id).map(x=>({r:x,overlap:skillsFor(x.job_id).filter(s=>skills.includes(s))})).filter(x=>x.overlap.length).sort((a,b)=>b.overlap.length-a.overlap.length).slice(0,4):[];
 const compare=r?[r,...nearby.map(x=>x.r)]:[],compareSkills=uniq(compare.flatMap(x=>skillsFor(x.job_id))).slice(0,9);
 return heading('직무 지도를 좁히며, 내가 할 일을 찾기','분류와 활동을 눌러 후보를 좁힌 뒤 한 직무를 선택하세요.')+`<div class="dashboard-grid">`+
 vCard('role-explore','직무 지도 · 사전 속 역할 분포',`<div class="role-map" data-chart="role-map">${categories.map(([name,n],i)=>`<button class="role-tile ${state.major===name?'selected':''}" data-major="${esc(name)}" style="--tile-color:${COLORS[i%COLORS.length]}"><strong>${n}<small>개 역할</small></strong><span>${esc(name)}</span></button>`).join('')}</div><div class="chips">${['코딩','AI·데이터','기계·전자','현장','영상·콘텐츠','연구'].map(a=>`<button data-activity="${a}" class="${state.activity.includes(a)?'selected':''}" aria-pressed="${state.activity.includes(a)}">${a}</button>`).join('')}</div><div class="source-toolbar"><label>직무·기술 검색<input id="roleSearch" value="${esc(state.roleQuery)}" placeholder="예: 자율비행, 정비"></label><button id="searchRoles">검색</button><button id="clearRoleFilters">후보 필터 해제</button></div><p class="chart-caption">${list.length}개 후보 / 전체 209개 사전 역할 · 현재 채용 직업 수가 아님</p><div class="role-list">${list.map(x=>`<button data-role="${x.job_id}" class="role-choice ${state.role===x.job_id?'selected':''}"><strong>${esc(x.job_title_ko)}</strong><small>${esc(x.evidence_type)}</small></button>`).join('')||empty('조건에 맞는 사전 역할 없음')}</div>`,'분류 타일 수치는 전체 사전 · 아래 후보에는 활동·분야·검색 필터 적용',{rule:'분류별 고유 job_id 개수. 분류 타일 크기는 동일하며 숫자로 규모 표시. 후보는 원본 직무 분류·활동 태그·선택 분야·검색의 교집합. 여러 활동은 OR.'})+
 vCard('role-detail',r?r.job_title_ko:'선택 직무의 업무와 연결',r?`<p class="role-summary">${esc(r.core_duties)}</p>`+pathDiagram([{label:'직무 사전',value:r.job_title_ko},{label:'준비 역량',value:skills.length+'개 항목',page:2},{label:'채용 분류 후보',value:roleMap(r)?.groups.join(' · ')||'미연결',page:3}])+chips(skills)+strip(`${r.evidence_type} · ${r.collected_date}`)+fold('근무처·기업 예시·직접 연결 공고',`<p>근무처: ${esc(r.workplace_types_raw)}</p><p>기업 예시: ${esc(r.employer_examples_raw)} · 현재 채용과 구분</p>${link(r.primary_source_url,r.primary_source_name)}${rows('TE').filter(x=>x.job_id===r.job_id).map(x=>`<p>${esc(x.actual_employer)} · ${link(x.actual_posting_url,x.actual_posting_title)}</p>`).join('')||'<p>이 세부직무의 직접 연결 공고 미확인</p>'}`):empty('왼쪽 지도에서 직무를 선택하세요','업무 → 준비 역량 → 채용 분류의 연결이 나타납니다.'),r?`${r.job_id} · 사전 기준 ${skills.length}개 역량`:'직무 선택 전')+
 vCard('adjacent-roles','주변 직무와 어떤 기술이 겹칠까?',r?heatmap(compare.map(x=>x.job_title_ko),compareSkills,compare.map(x=>compareSkills.map(s=>skillsFor(x.job_id).includes(s)?1:0)),{rowLabel:'직무 / 사전 역량'})+strip('1 = 사전 명시 · — = 미명시 · 선택 직무와 정확히 겹치는 역량 상위 4개 역할 / 최대 9개 기술')+`<div class="chips">${nearby.map(x=>`<button data-role="${x.r.job_id}">${esc(x.r.job_title_ko)} · 공통 ${x.overlap.length}</button>`).join('')}</div>`:empty('직무 선택 후 역량 교집합 행렬 표시'),'직무 사전의 정확한 기술명 일치 · 실제 이직률과 무관',{rule:'선택 직무와 skill_keyword 집합 교집합 개수 상위 4개. 선택 직무 포함 5행, 기술 합집합 앞 9개를 명시/미명시 행렬로 표현.',wide:true})+missingCard('interview')+`</div>`;
}
function educationPool(ignoreRegion=false){
 if(role())return courseCandidates(ignoreRegion);
 return rows('E').map(c=>({c,matches:[],sessions:rows('ES').filter(s=>s.course_id===c.course_id&&(ignoreRegion||!state.region||s.province_name===state.region||s.remote_mode==='원격'))})).filter(x=>x.sessions.length);
}
function courseItem({c,matches,sessions}){
 return `<article class="item ${state.course===c.course_id?'selected':''}"><div class="item-title">${esc(c.course_name)}</div><p>${esc(c.institution_name)} · ${num(c.total_training_hours)}시간 · ${esc(c.remote_mode)}</p><p class="chart-caption">${matches.length?'후보 이유: 과정명/NCS/관련 자격에 '+esc(matches.join(', '))+' 명시':'직무 선택 전의 전체 교육 참고 목록'} · 커리큘럼 미확인</p><button data-course="${c.course_id}">${state.course===c.course_id?'로드맵에 선택됨':'이 과정을 로드맵에 선택'}</button><details><summary>더보기 · ${sessions.length}회차 일정 / 비용 원문</summary>${table(['원본 비용 필드','금액'],['tuition_won','actual_training_cost_won','government_subsidy_won','expected_out_of_pocket_won'].map(k=>[k,num(c[k])+'원']))}<p class="chart-caption">${AUDIT.cost_issue_ids.includes(c.course_id)?'비용 산술관계 불일치':'비용 산술관계 일치'} · 개인별 최종 부담액 미확인. 원본 금액을 합산·차감하지 않습니다.</p>${table(['지역·방식','일정·기준일 상태','원문'],sessions.map(s=>[esc(s.province_name+' '+s.remote_mode),`${s.start_date} ~ ${s.end_date}<br>${schedule(s)}`,link(s.course_url)]))}<p class="chart-caption">${c.course_id} · course_id 직접 연결 · 실제 모집 상태와 날짜 상태는 다릅니다.</p></details></article>`;
}
function preparation(){
 const r=role(),m=roleMap(r),skills=r?skillsFor(r.job_id):[],known=skills.filter(s=>state.skills.includes(s)),pool=educationPool(),sessions=pool.flatMap(x=>x.sessions);
 const months=Array.from({length:12},(_,i)=>[i+1+'월',sessions.filter(s=>s.start_date.startsWith('2026-'+String(i+1).padStart(2,'0'))).length]);
 const keywords=rows('K').filter(k=>['프로그래밍언어','개발도구/SW','AI/ML','프레임워크/라이브러리','비행제어/드론플랫폼','하드웨어/전자'].includes(k.keyword_category_name)).sort((a,b)=>Number(b.posting_count)-Number(a.posting_count)).slice(0,12);
 const cert=rows('Q').filter(q=>q.certificate_type==='무인멀티콥터'&&q.full_year==='Y').slice(-6).map(q=>({...q,reference_year:q.year}));
 return heading('역량의 차이를 확인하고, 학습 기회를 고르기',r?r.job_title_ko:'직무 선택 전에는 보유 교육의 전체 분포를 보여줍니다.')+`<div class="dashboard-grid">`+
 vCard('skills','나의 역량 체크 · 사전 기준',r?`<div class="metric-grid two-metrics">${metric('선택한 보유 기술',known.length,'개','자기보고 · 숙련도 평가 아님')}${metric('추가 확인·학습',skills.length-known.length,'개','사전에서 미체크한 기술')}</div><div class="skill-summary" aria-label="${known.length}/${skills.length}개 사전 기술 체크">${skills.map(s=>`<span class="skill-block ${state.skills.includes(s)?'known':''}" title="${esc(s)}"></span>`).join('')}</div><div class="skill-grid">${skills.map(s=>`<label class="check role-skill"><input type="checkbox" data-skill="${esc(s)}" ${state.skills.includes(s)?'checked':''}>${esc(s)}</label>`).join('')}</div>${fold('국방 응용에 연결되는 기초 학습',rows('TM').filter(t=>m?.tech.includes(t.technology_id)).map(t=>`<p><strong>${esc(t.job_group)}</strong><br>${esc(t.learning_topics)}</p>`).join('')||empty('국방 기술 매핑 미확인'))}`:empty('관심 직무를 선택하면 역량 목록이 나타납니다.'),r?`${r.job_id} · ${skills.length}개 사전 기술 / 합격률 아님`:'직무 선택 전')+
 vCard('keyword-reference','전체 공고의 기술·도구 언급',hBars(keywords.map(k=>[k.keyword_normalized,Number(k.posting_count)]),{unit:'건',color:COLORS[0]})+strip('선택 직무와 무관한 전체 135개 공고 참고 · 해당 직무 요구 빈도로 해석하지 않음'),'전체 표본 n=135 · 다중 언급 · 필터 미적용',{rule:'기술·도구 관련 6개 원본 keyword_category_name에서 posting_count 상위 12개. 개별 공고 관계표가 없어 직무별 조인하지 않음.'})+
 vCard('courses','교육 시간과 개설 일정에서 후보 고르기',`<div class="metric-grid">${metric(r?'직무 관련 후보':'전체 참고 과정',pool.length,'과정',r?'명시 단어 기반 · 커리큘럼 미확인':'직무 선택 후 후보로 좁힘')}${metric('해당 회차',sessions.length,'회차','과정과 회차는 다른 단위')}${metric('원격 과정',pool.filter(x=>x.c.remote_mode==='원격').length,'과정','지역 선택에 관계없이 포함')}</div><div class="education-charts"><div><h4>훈련시간 × 보유 회차</h4>${courseScatter(pool)}</div><div><h4>2026년 월별 시작 회차</h4>${columns(months)}${strip('개강 일정의 분포 · 현재 모집 여부 미확인')}</div></div><h4>${r?'관련 교육 후보':'보유 교육 목록'} · ${state.course?'한 과정 선택됨':'점을 누르거나 목록에서 선택'}</h4><div class="compact-list">${pool.map(courseItem).join('')||empty('현재 보유 과정에서 후보 미확인')}</div>`,'선택 직무·지역 + 원격 · 과정별 course_id, 회차 offering_id',{wide:true,rule:'직무 선택 시 role-map-v1 명시 단어 후보, 미선택 시 전체 교육 참고. 산점도 x=total_training_hours, y=현재 범위 회차 수. 월별 시작 회차는 start_date 2026년 기준. 비용을 시각적 합산하지 않음.'})+
 vCard('portfolio','학습을 남길 결과물 · 3단계',m?`<p class="selected-title">${esc(m.project)}</p><div class="portfolio-stages"><div class="portfolio-stage"><strong>01 기초 재현</strong><small>작은 기능·절차<br>입력과 가정 기록</small></div><div class="portfolio-stage"><strong>02 업무 적용</strong><small>${esc(r.core_duties)}</small></div><div class="portfolio-stage"><strong>03 평가·설명</strong><small>실패 조건과 한계<br>검증 결과 정리</small></div></div><label class="check"><input data-project type="checkbox" ${state.project?'checked':''}>이 결과물 제안을 로드맵에 넣기</label>`:empty('직무 선택 후 결과물 제안 표시'),'직무 업무에서 착안한 편집 제안 · 기업 요구나 취업 보장 아님')+
 vCard('certifications','자격은 취득 규모와 채용 언급을 나누어 보기',lineChart(cert,'acquisition_count','건',COLORS[1])+strip('무인멀티콥터 · 완결 연도 최근 6개 · 고유 인원·취업자 수가 아님')+hBars(rows('K').filter(k=>k.keyword_category_name==='자격증').slice(0,6).map(k=>[k.keyword_normalized,Number(k.posting_count)]),{unit:'공고',color:COLORS[2]})+fold('직무의 자격 관련 원문',esc(r?.preferred_qualifications||'직무 선택 전')),'서로 다른 모집단 · 발급 통계와 135개 공고 언급을 직접 조인하지 않음',{rule:'Q 중 무인멀티콥터 full_year=Y 최근 6연도. K 자격증 카테고리 원본 앞 6개. 한 사람 복수 자격 가능, 법적 요건 판단 아님.'})+missingCard('curriculum')+missingCard('keywords')+`</div>`;
}
function postingsPage(){
 const posts=filteredPostings(),mapPosts=filteredPostings(true),m=roleMap(role());
 const companies=uniq(posts.map(p=>companyFor(p)?.company_id).filter(Boolean)).map(id=>rows('C').find(c=>c.company_id===id));
 const defenseCompanies=rows('C').filter(c=>/원문 직접|교차|방산인접/.test(c.defense_drone_relation_class)).slice(0,8);
 return heading('공고의 분포를 좁히고, 실제 조건을 확인하기','타일·직무 막대·경력 범주를 누르면 아래 수집 공고 목록이 연결됩니다.')+
 `<div class="posting-filter"><label>공고 직무<select data-state="group"><option value="">${m?'직무 규칙 후보':'전체 직무'}</option>${uniq(rows('J').map(p=>p.job_major_category)).map(g=>`<option ${state.group===g?'selected':''}>${esc(g)}</option>`).join('')}</select></label><label>경력<select data-state="career"><option value="">전체</option>${uniq(rows('J').map(p=>p.career_type)).map(c=>`<option ${state.career===c?'selected':''}>${c}</option>`).join('')}</select></label><label>기업 방산 근거<select data-state="defense"><option value="">전체 · 미확인 포함</option>${uniq(rows('J').map(defenseClass)).map(c=>`<option ${state.defense===c?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div><div class="dashboard-grid">`+
 vCard('posting-conditions','지역과 진입 조건',`<div class="metric-grid">${metric('선택 범위 공고',posts.length,'건','현재 모집 상태 미확인')}${metric('관측 기업',uniq(posts.map(p=>p.employer_name)).length,'개','수집 표본 내 기업명 기준')}${metric('전체 공고',rows('J').length,'건','관심 분야는 공고에 미적용')}</div><div class="jobs-chart-grid"><div><h4>근무지역 · 타일 선택</h4>${regionTiles(mapPosts,'province_name','공고')}</div><div><h4>경력 조건 · 범주 선택</h4>${stacked(count(posts,'career_type'),{action:'career',selected:state.career})}<h4>학력 조건</h4>${hBars(count(posts,'education_normalized'),{unit:'건',color:COLORS[0]})}</div></div>`,`${posts.length}개 고유 공고 · 지도만 지역 필터 미적용`,{wide:true,rule:'지도는 현재 직무·경력·방산 필터를 유지하고 지역만 해제한 고유 공고 수. 경력·학력은 모든 선택 조건을 적용한 고유 posting_id 수. 미확인 포함.'})+
 vCard('postings','직무별 수집 공고와 원문',hBars(count(posts,'job_major_category'),{unit:'공고',action:'group',selected:state.group})+`<div class="compact-list posting-list">${posts.map(postingItem).join('')||empty('현재 필터에서 관측 공고 0건','시장의 일자리 부재를 의미하지 않습니다.')}</div>`+`<div class="next">${next(4,'선택 공고와 내 조건 비교')}</div>`,`${posts.length}/135개 고유 공고 · 선택 직무는 넓은 분류의 규칙 후보`)+
 vCard('companies','공고 기업의 사업 분야',hBars(count(companies.flatMap(c=>uniq(rows('CB').filter(x=>x.company_id===c.company_id).map(x=>x.business_category)).map(b=>({category:b}))), 'category').slice(0,6),{unit:'기업',color:COLORS[1]})+strip(`기업정보 연결 ${posts.filter(p=>companyFor(p)).length} / 미연결 ${posts.filter(p=>!companyFor(p)).length}개 공고`)+`<div class="compact-list">${companies.map(companyItem).join('')||empty('해당 공고의 기업정보 미연결')}</div>`,'선택 공고 기업의 사업 관계 · 다중 사업 분야 · 미연결 공고 유지',{rule:'정확한 회사명 연결 후 company_id와 business_category별 중복 제거 기업 수. 한 기업은 여러 사업 분야에 포함될 수 있음.'})+
 vCard('defense-comparison','기업의 방산 근거 → 채용 직무',postingFlow(posts)+strip('왼쪽: 원본 방산 관계 분류 · 오른쪽: 표본 상위 6개 직무 + 나머지 합계 · 선 굵기: 공고 수'),'선택 공고 n='+posts.length+' · 미분류·미연결을 민간으로 바꾸지 않음',{wide:true,rule:'J의 각 고유 공고를 정확 이름 일치 C의 근거 집단과 J 직무 분류에 1회씩 배치. 상위 6개 직무 외는 기타 직무로 묶음. 연결선 합은 선택 공고 수와 같음.'})+
 vCard('defense-explore','채용과 별개인 방산 사업 탐색',stacked(count(rows('C'),'defense_drone_relation_class'),{unit:'기업'})+fold('관련 근거가 있는 기업 예시',defenseCompanies.map(companyItem).join('')),'기업 마스터 300개 전체 참고 · 직무·지역 필터 미적용',{rule:'기업 마스터 원본 관계 분류별 고유 company_id 수. 사례는 원문 직접·교차·인접 분류의 원본 앞 8개. 채용 관측 기업과 별개.'})+missingCard('live')+missingCard('defense')+`</div>`;
}
function roadmap(){
 const r=role(),skills=r?skillsFor(r.job_id):[],known=skills.filter(s=>state.skills.includes(s)),missing=skills.filter(s=>!state.skills.includes(s)),p=rows('J').find(x=>x.posting_id===state.posting),course=rows('E').find(x=>x.course_id===state.course),m=roleMap(r);
 return heading('탐색한 정보를, 다음 준비 행동으로','선택한 직무·역량·교육·공고를 한 경로에서 확인하세요.')+
 vCard('action-plan','내가 선택한 준비 경로',pathDiagram([{label:'목표 직무',value:r?.job_title_ko||'선택 전',active:!!r,page:1},{label:'사전 역량',value:r?known.length+' / '+skills.length+'개 체크':'직무 선택 전',note:'능력·합격률 평가 아님',active:!!known.length,page:2},{label:'학습 기회',value:course?.course_name||'교육 후보 선택 전',active:!!course,page:2},{label:'제작할 결과물',value:state.project&&m?m.project:'프로젝트 선택 전',active:state.project,page:2},{label:'공고 조건 확인',value:p?.employer_name||'비교 공고 선택 전',note:p?.title,active:!!p,page:3}],{kind:'roadmap-path'})+`<div class="action-checks">${[['learn',missing.length?'부족 역량 중 한 항목 학습 계획 세우기':'관심 직무와 실제 숙련도 점검하기'],['course',course?'과정 커리큘럼·비용·일정 확인하기':'교육 또는 프로젝트 후보 선택하기'],['posting',p?'모집 상태·필수조건 원문 확인하기':'공고 선택 후 조건 비교하기']].map(([key,text],i)=>`<label class="check"><input type="checkbox" data-check="${key}" ${state.checks[key]?'checked':''}><span><small>NEXT ${i+1}</small>${text}</span></label>`).join('')}</div>`,'개인 선택을 모은 학습·결과물·원문 확인 계획 · 취업 시점 예측 없음',{wide:true})+
 `<div class="dashboard-grid">`+
 vCard('personal-input','나의 조건과 사전 기술',`<div class="source-toolbar"><label>학력<select data-state="education"><option value="">입력하지 않음</option>${['고졸','초대졸','대졸','석사','박사'].map(x=>`<option ${state.education===x?'selected':''}>${x}</option>`).join('')}</select></label><label>경력<select data-state="experience"><option value="">입력하지 않음</option>${['신입','경력'].map(x=>`<option ${state.experience===x?'selected':''}>${x}</option>`).join('')}</select></label><label>관련 경력 연수<input type="number" min="0" step="0.5" data-state="years" value="${esc(state.years)}" placeholder="미입력"></label></div><div class="skill-summary">${skills.map(s=>`<span class="skill-block ${state.skills.includes(s)?'known':''}" title="${esc(s)}"></span>`).join('')}</div><div class="skill-grid">${skills.map(s=>`<label class="check role-skill"><input type="checkbox" data-skill="${esc(s)}" ${state.skills.includes(s)?'checked':''}>${esc(s)}</label>`).join('')}</div>${r?strip(`${known.length}/${skills.length}개 체크 · 미체크: ${missing.join(', ')||'없음'}`):empty('관심 직무 선택 후 기술 체크 가능')}`,'선택 입력 + 사전 기준 정확 일치 · 개인 입력은 외부 전송하지 않음')+
 vCard('condition-match','선택 공고의 조건 신호',p?`<p class="selected-title">${esc(p.employer_name)}</p><p class="chart-caption">${esc(p.title)}</p><div class="condition-grid">${conditionCompare(p).map(([key,basis,status])=>`<div class="condition-tile ${status==='확인된 조건과 일치'?'match':status==='불일치'?'miss':''}"><strong>${esc(key)}</strong><span class="${status==='불일치'?'status-miss':status==='미확인'?'status-unknown':'status-match'}">${status==='확인된 조건과 일치'?'확인 조건 일치':status}</span><small>${esc(basis)}</small></div>`).join('')}</div>${strip('일치가 있어도 지원 가능 확정이 아닙니다. 전체 필수조건과 모집 상태를 확인하세요.')}${link(p.primary_source_url)}`:empty('채용 화면에서 비교할 공고를 선택하세요'),p?`${p.posting_id} · 일치 / 불일치 / 미확인 · 종합 점수 없음`:'공고 선택 전')+missingCard('outcomes')+missingCard('mobility')+`</div>`;
}
