const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),out=path.join(root,'test-output');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(root,'dist/index.html')).href);await page.locator('#app').waitFor({state:'visible'});
 assert.equal(await page.locator('[data-module="industry-size"] svg').count(),3);
 const original=await page.locator('[data-module="industry-size"]').innerText();
 await page.locator('[data-field="국방·방산"]').click();
 assert.equal(await page.locator('[data-module="industry-size"]').innerText(),original);
 assert.equal(await page.evaluate(()=>rows('R').filter(r=>r.ranking_inclusion_flag==='1'&&r.defense_flag==='1').length),818);
 await page.locator('#reset').click();await page.screenshot({path:path.join(out,'v2-industry.png')});
 await page.locator('#nav [data-page="1"]').click();
 await page.locator('[data-major]').first().click();
 assert.equal(await page.evaluate(()=>matchingRoles().every(r=>r.major_category===state.major)),true);
 await page.locator('#clearRoleFilters').click();
 const ai=await page.evaluate(()=>rows('T').find(r=>roleMap(r)?.id==='AI').job_id);
 await page.selectOption('#role',ai);
 assert.ok(await page.locator('[data-chart="heatmap"] td').count()>0);
 const matrix=await page.evaluate(()=>{const t=skillsFor(state.role);return {skills:t,html:document.querySelector('[data-chart="heatmap"]').innerText};});
 assert.ok(matrix.skills.every(s=>matrix.html.includes(s)));
 await page.screenshot({path:path.join(out,'v2-roles.png'),fullPage:true});
 await page.locator('#nav [data-page="2"]').click();
 const points=page.locator('circle[data-course]');assert.ok(await points.count()>0);
 const id=await points.first().getAttribute('data-course');await points.first().focus();await page.keyboard.press('Enter');
 assert.equal(await page.evaluate(()=>state.course),id);
 const months=await page.locator('[data-chart="columns"] .column>strong').allTextContents();
 assert.equal(months.reduce((a,b)=>a+Number(b.replaceAll(',','')),0),await page.evaluate(()=>educationPool().flatMap(x=>x.sessions).length));
 await page.screenshot({path:path.join(out,'v2-preparation.png'),fullPage:true});
 await page.locator('#reset').click();await page.locator('#nav [data-page="3"]').click();
 const tiles=await page.locator('.map-tile strong').allTextContents();assert.equal(tiles.reduce((a,b)=>a+Number(b),0),135);
 await page.locator('[data-region="경기"]').click();
 assert.equal(await page.evaluate(()=>filteredPostings().length),49);
 await page.locator('[data-career="경력"]').first().click();
 assert.equal(await page.evaluate(()=>filteredPostings().every(p=>p.province_name==='경기'&&p.career_type==='경력')),true);
 await page.locator('#reset').click();
 const flowTotal=Number(await page.locator('[data-chart="sankey"]').getAttribute('data-flow-total'));
 const links=await page.locator('[data-chart="sankey"] path title').allTextContents();
 assert.equal(links.reduce((a,s)=>a+Number(s.match(/: (\d+)개/)[1]),0),flowTotal);assert.equal(flowTotal,135);
 await page.screenshot({path:path.join(out,'v2-postings.png'),fullPage:true});
 await page.locator('[data-module="defense-comparison"]').screenshot({path:path.join(out,'v2-sankey.png')});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'v2-mobile.png')});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:1500,height:1000});
 await page.selectOption('#role',ai);await page.locator('#nav [data-page="2"]').click();
 const exported=await page.waitForFunction(()=>document.querySelectorAll('circle[data-course]').length>0);await exported.dispose();
 const filePromise=page.waitForEvent('download');await page.locator('#save').click();const file=await filePromise;
 await file.saveAs(path.join(out,'visual-export.html'));
 await page.goto(pathToFileURL(path.join(out,'visual-export.html')).href);await page.locator('#app').waitFor({state:'visible'});
 assert.ok(await page.locator('circle[data-course]').count()>0);
 assert.equal(errors.length,0,errors.join('\n'));
 const result={status:'PASS',checks:['three real-data trend charts','industry scope stable under field filter','field count from source','role-map filtering','skill matrix matches taxonomy','scatter keyboard selection','monthly counts reconcile to sessions','map total=135 and Gyeonggi=49','combined chart filters','Sankey links sum=135','mobile no page overflow','visual HTML export restores charts','no runtime errors']};
 fs.writeFileSync(path.join(out,'visual-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
